Indah Wulan Lestari

2009106027

In [2]:
import numpy as np
import tensorflow as tf

### Membuat tensor dengan shape(5,5) dengan menggunakan nilai random

In [4]:
random_tensor = tf.random.normal([5,5], seed=1)

In [6]:
random_tensor.numpy()

array([[-0.32386488,  0.99133694,  0.14024267,  1.2573972 ,  0.09992335],
       [ 0.18983224, -0.28711194, -1.7413595 ,  1.8718754 , -2.0104504 ],
       [-1.4673029 , -1.2721989 , -0.7803738 ,  0.94073033, -0.06164822],
       [-2.0842526 ,  0.61423135, -1.451092  , -0.88693523, -0.96740866],
       [ 0.94831836, -0.6974499 ,  0.5391437 , -0.52970064, -2.0105364 ]],
      dtype=float32)

### Membuat tensor dengan shape (5,5) dari list dengan nilai bilangan prima dalam variabel tensor

In [9]:
list1 = [2,3,5,7,11], [13,17, 19, 23, 29], [31, 37, 41, 43, 47], [53, 59, 61, 67, 71], [73, 79, 83, 89, 97]

prime_tensor = tf.convert_to_tensor(list1, dtype = tf.float32)

In [10]:
prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)

### Menampilkan Dimensi kedua variabel

In [12]:
print ("Dimensi Pada Variabel Random : ", random_tensor.shape)
print ("Dimensi Pada Variabel Prima : ", prime_tensor.shape)

Dimensi Pada Variabel Random :  (5, 5)
Dimensi Pada Variabel Prima :  (5, 5)


### Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

* Penjumlahan

In [13]:
print(tf.add(random_tensor, prime_tensor))

tf.Tensor(
[[ 1.6761351  3.9913368  5.1402426  8.257397  11.099923 ]
 [13.189833  16.712889  17.25864   24.871876  26.98955  ]
 [29.532698  35.727802  40.219627  43.94073   46.93835  ]
 [50.91575   59.61423   59.54891   66.11307   70.03259  ]
 [73.94832   78.30255   83.53915   88.4703    94.98946  ]], shape=(5, 5), dtype=float32)


* Perkalian

In [14]:
print(tf.multiply(random_tensor, prime_tensor))

tf.Tensor(
[[  -0.64772975    2.974011      0.70121336    8.801781      1.0991569 ]
 [   2.4678192    -4.880903    -33.08583      43.053135    -58.303062  ]
 [ -45.48639     -47.07136     -31.995327     40.451405     -2.8974664 ]
 [-110.465385     36.23965     -88.51661     -59.42466     -68.68601   ]
 [  69.22724     -55.098545     44.748924    -47.143356   -195.02203   ]], shape=(5, 5), dtype=float32)


* Pengurangan

In [15]:
print(tf.subtract(random_tensor, prime_tensor))

tf.Tensor(
[[ -2.323865   -2.0086632  -4.8597574  -5.742603  -10.900077 ]
 [-12.810167  -17.287111  -20.74136   -21.128124  -31.01045  ]
 [-32.467304  -38.272198  -41.780373  -42.05927   -47.06165  ]
 [-55.08425   -58.38577   -62.45109   -67.88693   -71.96741  ]
 [-72.05168   -79.69745   -82.46085   -89.5297    -99.01054  ]], shape=(5, 5), dtype=float32)


* Pembagian

In [16]:
print(tf.divide(random_tensor, prime_tensor))

tf.Tensor(
[[-0.16193244  0.33044565  0.02804853  0.17962816  0.00908394]
 [ 0.01460248 -0.01688894 -0.0916505   0.08138589 -0.06932587]
 [-0.04733235 -0.03438376 -0.01903351  0.02187745 -0.00131166]
 [-0.03932552  0.0104107  -0.02378839 -0.01323784 -0.01362547]
 [ 0.01299066 -0.00882848  0.00649571 -0.00595169 -0.02072718]], shape=(5, 5), dtype=float32)


* Logaritma

In [18]:
print(tf.math.log(random_tensor, prime_tensor))

tf.Tensor(
[[        nan -0.0087008  -1.964381    0.22904386 -2.3033519 ]
 [-1.6616145          nan         nan  0.62694085         nan]
 [        nan         nan         nan -0.06109876         nan]
 [        nan -0.48738366         nan         nan         nan]
 [-0.05306501         nan -0.6177732          nan         nan]], shape=(5, 5), dtype=float32)


#### Tampilkan nilai maksimal dan minimal dari variable random_tensor

* Menampilkan nilai maksimal dari variabel random tensor

In [20]:
tf.argmax(random_tensor, axis = 0).numpy()


array([4, 0, 4, 1, 0], dtype=int64)

* Menampilkan nilai minimal dari variabel random

In [21]:
tf.argmin(random_tensor, axis=0).numpy()

array([3, 2, 1, 3, 4], dtype=int64)

#### Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [24]:
print("Size original : ",random_tensor.shape,prime_tensor.shape)
concated_tensor = tf.concat([random_tensor,prime_tensor],axis=0)
print("Size concatenated : ",concated_tensor.shape)

Size original :  (5, 5) (5, 5)
Size concatenated :  (10, 5)


#### Tampilkan hasil sorting dari kedua variable di atas. (descending)

* Random Tensor

In [28]:
random_tensor.numpy()

array([[-0.32386488,  0.99133694,  0.14024267,  1.2573972 ,  0.09992335],
       [ 0.18983224, -0.28711194, -1.7413595 ,  1.8718754 , -2.0104504 ],
       [-1.4673029 , -1.2721989 , -0.7803738 ,  0.94073033, -0.06164822],
       [-2.0842526 ,  0.61423135, -1.451092  , -0.88693523, -0.96740866],
       [ 0.94831836, -0.6974499 ,  0.5391437 , -0.52970064, -2.0105364 ]],
      dtype=float32)

In [32]:
sort_random = tf.sort(random_tensor, direction="DESCENDING")
sort_random.numpy()

array([[ 1.2573972 ,  0.99133694,  0.14024267,  0.09992335, -0.32386488],
       [ 1.8718754 ,  0.18983224, -0.28711194, -1.7413595 , -2.0104504 ],
       [ 0.94073033, -0.06164822, -0.7803738 , -1.2721989 , -1.4673029 ],
       [ 0.61423135, -0.88693523, -0.96740866, -1.451092  , -2.0842526 ],
       [ 0.94831836,  0.5391437 , -0.52970064, -0.6974499 , -2.0105364 ]],
      dtype=float32)

In [33]:
sort_prime = tf.sort(prime_tensor, direction = "DESCENDING")
sort_prime.numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)